<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AgentSwarm.Bridges.Telegram\AgentSwarm.Bridges.Telegram.csproj" />
    <ProjectReference Include="..\AgentSwarm.Core\AgentSwarm.Core.csproj" />
    <ProjectReference Include="..\AgentSwarm.Contracts\AgentSwarm.Contracts.csproj" />
    <ProjectReference Include="..\AgentSwarm.Providers.OpenAi\AgentSwarm.Providers.OpenAi.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
